# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  acessochallengeapi:
    image: acessochallengeapi
    build:
      context: .
      dockerfile: AcessoChallenge.Api/Dockerfile
    ports:
      - 5486:5486
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
